models/Articulos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "articulos".
 *
 * @property int $id
 * @property string|null $titulo
 * @property string|null $texto_corto
 * @property string|null $texto_largo
 * @property string|null $foto
 */
class Articulos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'articulos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['titulo', 'texto_corto', 'texto_largo', 'foto'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'titulo' => 'Titulo',
            'texto_corto' => 'Texto Corto',
            'texto_largo' => 'Texto Largo',
            'foto' => 'Foto',
        ];
    }
}

models/Noticias.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "noticias".
 *
 * @property int $id
 * @property string|null $titulo
 * @property string|null $foto
 */
class Noticias extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'noticias';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['titulo', 'foto'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'titulo' => 'Titulo',
            'foto' => 'Foto',
        ];
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\Noticias;
use yii\data\ActiveDataProvider;
use app\models\Articulos;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionNoticias()
    {
        $query = Noticias::find()->select("noticias.*");
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        
        return $this->render('noticias',[
            "dataProvider" => $dataProvider,
        ]);
    }

    public function actionArticulos()
    {
        $query = Articulos::find()->select("articulos.*");
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        
        return $this->render('articulos',[
            "dataProvider" => $dataProvider,
        ]);
    }

    public function actionMostrar_articulo_texto_largo($id) {
        $articulo = Articulos::findOne($id);
        return $this->render("articulo_texto_largo",[
            "articulo" => $articulo,
        ]);
    }
    
    public function actionTodo() {
        $queryNoticias = Noticias::find()->select("noticias.*");
        
        $dataProviderNoticias = new ActiveDataProvider([
            'query' => $queryNoticias,
        ]);
        
        $queryArticulos = Articulos::find()->select("articulos.*");
        
        $dataProviderArticulos = new ActiveDataProvider([
            'query' => $queryArticulos,
        ]);
        
        return $this->render("todo", [
            "dataProviderNoticias" => $dataProviderNoticias,
            "dataProviderArticulos" => $dataProviderArticulos,
        ]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Noticias', 'url' => ['/site/noticias']],
            ['label' => 'Articulos', 'url' => ['/site/articulos']],
            ['label' => 'Todo', 'url' => ['/site/todo']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Oscar Megía López 2020</p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/_articulos.php
<?php
use app\widgets\Articulos;
?>

<?= Articulos::widget([
      'id' => $model->id,
      'foto' => $model->foto,
      'titulo' => $model->titulo,
      'texto_corto' => $model->texto_corto,
    ]) ?>

views/site/_noticias.php
<?php
use app\widgets\Noticias;
?>

<?= Noticias::widget([
    'titulo' => $model->titulo,
    'texto' => $model->texto,
    'foto' => $model->foto,
]) ?>

views/site/articulo_texto_largo.php
<div class="col-12">
  <div class="thumbnail">
    <div class="caption">
      <h1><?= $articulo->titulo ?></h1>
      <p><?= $articulo->texto_largo ?></p>
    </div>
  </div>
</div>

views/site/articulos.php
<?php 
use yii\widgets\ListView;
?>

<?= ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_articulos',
    'layout' => '{items}',
]) ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/noticias.php
<?php 
use yii\widgets\ListView;
?>

<?= ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_noticias',
    'layout' => '{items}',
]) ?>

views/site/todo.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;
?>

<?= GridView::widget([
    'dataProvider' => $dataProviderNoticias,
    'columns' => [
        'id',
        'titulo',
        'texto',
        [
            'label' => 'Foto',
            'format' => 'raw',
            'value' => function($data) {
                return Html::img("@web/imgs/" . $data->foto, ['alt' => $data->foto, 'width' => '100px']);
            }
        ]
    ]
]) ?>

<?= GridView::widget([
    'dataProvider' => $dataProviderArticulos,
    'columns' => [
        'titulo',
        'texto_corto',
    ]
]) ?>